all: main.c compress.c
	gcc  main.c compress.c -o odev2

example1: main.c
	gcc main.c -o main -Wall -ansi -pedantic-errors

example2: compress.c
	gcc compress.c -o compress -Wall -ansi -pedantic-errors

